#!/usr/bin/env bash
# This script configures a new Ubuntu machine by installing Nginx.
# It sets up Nginx to listen on port 80 and serve a page returning a "Hello World" string.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nSetting up some minor configurations.\n"

# Start the nginx service
sudo service nginx start

# Allow nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Grant the user ownership of website files for easier editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart nginx to apply changes
sudo service nginx restart

echo -e "\nSetup completed. ✅\n"
